version: "3"
services:

  nftmart:
    restart: always
    image: nftmart/node:staging-v2
    volumes:
    - /etc/localtime:/etc/localtime
    - ./entrypoint.sh:/entrypoint.sh
    - ./state/:/data/
    - ./stagingRaw.json/:/stagingRaw.json
    ports:
    - 30333:30333
    entrypoint: [ "/entrypoint.sh" ]
    command:
    - --name=${NAME:-changeme}
    - --base-path=/data/
    - --validator
    - --ws-port=9944
    - --port=30333
    - --chain=/stagingRaw.json
