version: "3"
services:

  nftmart:
    restart: always
    image: nftmart/node:staging
    volumes:
    - /etc/localtime:/etc/localtime
    - ./entrypoint.sh:/entrypoint.sh
    - ./data/:/data/
    ports:
    - 30333:30333
    entrypoint: [ "/entrypoint.sh" ]
    command:
    - --base-path=/data/
    - --validator
    - --ws-port=9944
    - --port=30333
