version: "3.8"
services:
  caddy:
    restart: always
    image: btwiuse/polkadot-js-apps:nftmart
    command:
    - caddy
    - run
    - -config
    - /Caddyfile
    volumes:
    - ./Caddyfile:/Caddyfile
    ports:
    - 2021:80
  nftmart:
    restart: always
    env_file: .env
    image: btwiuse/nftmart:beta
    volumes:
    - ./entrypoint.rc:/entrypoint.rc
    - ./state/node5:/data/state/node5
    ports:
    - "${PORT5}:${PORT5}"
    - "${RPC_PORT5}:${RPC_PORT5}"
    - "${WS_PORT5}:${WS_PORT5}"
    entrypoint: [ "bash", "-c" ]
    command:
    - source /entrypoint.rc && node5
