version: "3.8"
services:

  caddy:
    restart: always
    image: btwiuse/polkadot-js-apps:nftmart
    command:
    - caddy
    - run
    - -config
    - /Caddyfile
    volumes:
    - ./Caddyfile:/Caddyfile
    ports:
    - 9944 # random port

  nftmart:
    restart: always
    image: btwiuse/nftmart:beta
    volumes:
    - ./entrypoint.sh:/entrypoint.sh
    - ./state/validator:/data/state/validator
  # ports:
  # - 30333:30333
    entrypoint: [ "/entrypoint.sh" ]
    command:
    - --base-path=/data/state/validator
    - --validator

  add-validator:
    profiles: ["add-validator"]
    image: btwiuse/nftmart:cli
    pull_policy: always
    command:
    - add-validator
    - ./config
    volumes:
    - ./config:/app/config
