version: "3.8"
services:
  caddy:
    restart: always
    image: btwiuse/polkadot-js-apps:nftmart
    command:
    - caddy
    - run
    - -config
    - /Caddyfile
    volumes:
    - ./Caddyfile:/Caddyfile
    ports:
    - 9944:9944
  nftmart:
    restart: always
    env_file: .env
    image: btwiuse/nftmart:beta
    volumes:
    - ./entrypoint.rc:/entrypoint.rc
    - ./state/node5:/data/state/node5
    ports:
    - 30333:30333
  # - 9615:9615
  # - 9933:9933
    entrypoint: [ "/entrypoint.rc" ]
    command:
    - --base-path=/data/state/node5
    - --validator
    - --node-key=${NODE_KEY5}
    - --bootnodes=/dns/${IP1}/tcp/${PORT1}/p2p/${NODE_PEER_ID1}
    - --bootnodes=/dns/${IP2}/tcp/${PORT2}/p2p/${NODE_PEER_ID2}
    - --ws-port=9944
    - --port=30333
  # - --prometheus-port=9615
  # - --rpc-port=9933
